# Generated by Django 5.0.6 on 2024-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='selected_image',
            field=models.CharField(choices=[('ce_1.jpeg', 'Image 1'), ('ce_2.jpeg', 'Image 2'), ('ce_3.jpeg', 'Image 3'), ('ce_4t.jpeg', 'Image 4'), ('ce_5t.jpeg', 'Image 5')], max_length=50),
        ),
    ]
