# Generated by Django 5.0.6 on 2024-06-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0003_codes_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='monthActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='codes',
            name='yearActive',
            field=models.BooleanField(default=True),
        ),
    ]
