# Generated by Django 5.0.6 on 2024-06-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0004_codes_monthactive_codes_yearactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='amountOfMonthUsers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codes',
            name='amountOfYearUsers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
