# Generated by Django 5.0.6 on 2024-06-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0005_codes_amountofmonthusers_codes_amountofyearusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image4',
            new_name='Shokr',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image1',
            new_name='hodor',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image2',
            new_name='tafwoq',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image3',
            new_name='tahnqa',
        ),
    ]
