# Generated by Django 5.0.6 on 2024-06-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0006_rename_image4_images_shokr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Shokr',
            field=models.ImageField(default='images/ce_4.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='hodor',
            field=models.ImageField(default='images/ce_1.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='tafwoq',
            field=models.ImageField(default='images/ce_2.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='tahnqa',
            field=models.ImageField(default='images/ce_3.jpg', upload_to='images/'),
        ),
    ]
