# Generated by Django 5.0.6 on 2024-07-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0008_rename_monthactive_codes_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='codes',
        ),
    ]
