# Generated by Django 5.0.6 on 2024-07-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0010_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='data_of_end',
            field=models.DateField(default='2024-07-05'),
        ),
    ]
