# Generated by Django 5.0.6 on 2024-07-05 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0011_alter_codes_data_of_end'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='active',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='amount_of_users',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='code',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='data_of_creation',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='data_of_end',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='type_of_code',
        ),
        migrations.AddField(
            model_name='codes',
            name='amountOfMonthUsers',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='codes',
            name='amountOfYearUsers',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='codes',
            name='monthActive',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='codes',
            name='monthCode',
            field=models.CharField(max_length=10000000, null=True),
        ),
        migrations.AddField(
            model_name='codes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codes',
            name='yearActive',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='codes',
            name='yearCode',
            field=models.CharField(max_length=10000000, null=True),
        ),
    ]
