# Generated by Django 5.0.6 on 2024-07-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0012_remove_codes_active_remove_codes_amount_of_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codes',
            old_name='monthActive',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='codes',
            old_name='amountOfMonthUsers',
            new_name='amountOfUsers',
        ),
        migrations.RenameField(
            model_name='codes',
            old_name='monthCode',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='amountOfYearUsers',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='yearActive',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='yearCode',
        ),
        migrations.AddField(
            model_name='codes',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='codes',
            name='date_of_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='codes',
            name='type_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
