# Generated by Django 5.0.6 on 2024-07-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0013_rename_monthactive_codes_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='codes',
            name='date_of_end',
            field=models.DateTimeField(null=True),
        ),
    ]
